### ISSUE TITLE
¿De qué vamos a hacer la página? 

### ISSUE THREAD

**Issue by AlvMur** [gloriacaro97/Despl-Grupo4-2020#1]
Pues lo dicho, la página a qué la vamos a orientar y eso. Es que sinceramente no se me ocurren ideas

**Comment by MiriamVR** [comment]
¡Hola! Yo he pensado que podríamos aprovechar que viene la Navidad y hacer una web de un evento o fiesta, en el Fibes por ejemplo... Metemos imagenes, horarios y tal... ¿Qué os parece?

**Comment by MiriamVR** [comment]
Por ejemplo, algo así [https://www.navidadmadrid.com/](url)

**Comment by jcsotpin** [comment]
pues lo podemos organizar con un titulo, una estrucura con elemenos "card" donde meter cosas  y un footer para empezar

**Comment by MiriamVR** [comment]
Nice, me parece bien. Las cards podrían ser los eventos, ponemos ahí la hora el día y eso... ¿Le metemos un nav? Aunque solo tenga una página, yo creo que queda mas profesional así

**Comment by gloriacaro97** [comment]
A mí me parece perfe. Yo le metería un carrusel, que siempre hace atractiva la página y lo del nav me parece bien también, aunque sea para ir a las distintas partes de la página principal

**Comment by gloriacaro97** [comment]
Si os parece, voy a ir haciendo el carrusel con algunas imágenes con cosas tipo comidas temáticas y decoraciones y eso. Si no os gusta alguna pues me avisáis y se cambia la que sea.

**Comment by MiriamVR** [comment]
Por mi genial, yo creo que voy a empezar con el nav que tengo ya una idea más o menos definida. ¿El resto? ¿Qué se os ocurre?

**Comment by AlvMur** [comment]
Vale, pues yo hago un footer en principio y luego según avance la página vemos que más cosas meter.

**Comment by MiriamVR** [comment]
Cool. 
Miriam --> Nav
Gloria --> Carousel
Álvaro --> Footer

**Comment by jcsotpin** [comment]
Miriam --> Nav
Gloria --> Carousel
Álvaro --> Footer
Juan Carlos --> Card

intentaré hacer un bloque con 3 card que queda muy vistoso de esta manera

**Comment by gloriacaro97** [comment]
Yo voy a usar boostrap. Si vosotros también lo vais a usar, si queréis actualizo el index con los links y los scripts de bootstrap que yo ya los tengo puestos

**Comment by AlvMur** [comment]
Lo lógico sería que todos utilicemos la misma tecnología en nuestro proyecto. Así que sería menester, que usaramos Bootstrap todos.

**Comment by MiriamVR** [comment]
¿Quién se encargar de rellenar las meta? Puedo hacerlo yo si quereis

**Comment by JoseDumen** [comment]
Miriam --> Nav
Gloria --> Carousel
Álvaro --> Footer
Juan Carlos --> Card
José Francisco --> Div con video
