### ISSUE TITLE
¿Colores?

### ISSUE THREAD

**Issue by MiriamVR** [gloriacaro97/Despl-Grupo4-2020#2]
Hola! Os dejo por aquí unas paletas de colores para la web que me han gustado. Subid vosotros más si queréis y hacemos votación con iconos a ver con cual nos quedamos.

**Comment by MiriamVR** [comment]
![](https://media.discordapp.net/attachments/775629835909201930/775641486783807508/2Q.png)

**Comment by MiriamVR** [comment]
![](https://media.discordapp.net/attachments/775629835909201930/775642020441227264/cvetovaya-palitra-1805.png)

**Comment by jcsotpin** [comment]
Con esas imgágenes yo creo que se cubren los colores más característicos.
A mi me parecen correctos, dale pulgarcito arriba

**Comment by gloriacaro97** [comment]
Yo tiraría más a la segunda, me resulta más navideña creo que por los verdes

**Comment by MiriamVR** [comment]
A mi me gusta la segunda más también, le doy like

**Comment by AlvMur** [comment]
La segunda imagen creo que sería más acertada. Los colores evocan más sensación de navidad

**Comment by MiriamVR** [comment]
Os dejo por aquí los códigos html de los colores de la más votada:

******************************************
1_Rojo ---> #FF3314
2_Ocre ---> #D5AD56
3_Beige ---> #F8E19F
4_Verde ---> #018667
5_Verde oscuro ---> #003F2D
******************************************

**Comment by gloriacaro97** [comment]
Ay, perfe. Gracias, Miriam

**Comment by JoseDumen** [comment]
Al estar resuelto el tema de los colores de la página, procedo a cerrar el hilo.
