### ISSUE TITLE
Icono Navegador

### ISSUE THREAD

**Issue by MiriamVR** [gloriacaro97/Despl-Grupo4-2020#3]
Hola de nuevo. ¿Os parece bien este icono para el logo de la web? Lo voy a vectorizar y lo pongo en blanco mejor para que destaque mas

![copo-de-nieve](https://user-images.githubusercontent.com/51456018/99840874-9d92b800-2b6d-11eb-9d85-4ebbec5f1346.png)

**Comment by jcsotpin** [comment]
Esta muy chulo. Tengo visto una forma de meterle animación y que vaya girando, si lo consigo te paso el código

**Comment by MiriamVR** [comment]
Que guay eso 👀 vale, me lo apunto

**Comment by jcsotpin** [comment]
@MiriamVR , prueba a ver como queda la animación en el nav

esto en el css
`@keyframes icono{
    0%   {transform: rotate(0deg);}
    20%  {transform: rotate(0deg);}
  
    80%  {transform: rotate(360deg);}
    100% {transform: rotate(360deg);}
}
.icono{ 
    position: relative;
    animation: icono 10s linear -1s infinite normal;
 `
"icono" es el nombre de la clase, ponle el que tu tengas. No queda exactamente como yo quería, pero no se si tocando números queda algo bueno

**Comment by MiriamVR** [comment]
Vale, voy a probar

**Comment by MiriamVR** [comment]
Queda genial!! He cambiado algunos números, ahora me decís que os parece
