### ISSUE TITLE
Duda con links en el Footer

### ISSUE THREAD

**Issue by AlvMur** [gloriacaro97/Despl-Grupo4-2020#4]
He actualizado el proyecto añadiendo el footer, mi duda es que con el color de fondo los links no se ven correctamente con el color de base. ¿Debería poner los links en blanco como el resto del texto del footer o poner algún otro tipo de color para que se entienda que son links?

**Comment by JoseDumen** [comment]
Vale, es cierto que cuesta verlos un poco. Blanco estaria bien

**Comment by jcsotpin** [comment]
si cambialos, ve probando distintntos colores o resaltarlo con un subrayado o algo

**Comment by MiriamVR** [comment]
Yo lo pondría en blanco o quizás en beige para darle uso al color ese de la paleta

**Comment by gloriacaro97** [comment]
Yo en blanco no sé si lo pondría porque no sé si se va a diferenciar del resto del texto

**Comment by JoseDumen** [comment]
Lo suyo sería ponerlo a lo mejor del mismo color de la parte de contacto.
