### ISSUE TITLE
Ideas para las tarjetas

### ISSUE THREAD

**Issue by jcsotpin** [gloriacaro97/Despl-Grupo4-2020#5]
Gente, estoy pensando en ideas para los eventos o información que poner en las tarjetas y se me ha ocurrido esta maravilla XD
Decidme que os parece y si teneis mas ideas decidmelas.

![Papa-Noel-vs-Reyes-Magos](https://user-images.githubusercontent.com/73720448/99875075-14bb6100-2bed-11eb-8c8b-5702f0d577f4.jpg)

**Comment by gloriacaro97** [comment]
A ver, la idea me hace gracia, aunque no sé cómo de navideña es la lucha libre jajajajajjajaja

**Comment by JoseDumen** [comment]
No se yo si seria lo más apropiado para una página de evento navideño. Piensa en los niños.

**Comment by gloriacaro97** [comment]
Se puede poner en plan competición y la gente haga votación al llegar al evento y al final pues no sé, que se le de un premio o se regale algo a la gente de uno o de otro o algo así (yo buscando formas de meter la foto porque me hace gracia xd)

**Comment by JoseDumen** [comment]
Pensandolo mejor si se plantea bien todo el tema de la competición puede resultar gracioso tanto para padres como hijos. Y si ademas se ponen premios curiosos todo sera más atractivo.
