### ISSUE TITLE
Musica

### ISSUE THREAD

**Issue by jcsotpin** [gloriacaro97/Despl-Grupo4-2020#7]
Gente, he estado probando y tengo un código para meterle música de fondo a la pagina. He escogido esta, pero si encontrais otra que os guste más pasadmelo.
https://www.youtube.com/watch?v=3_a-7zeKqz8

**Comment by MiriamVR** [comment]
A mi me gusta, muy de la época jeje. Gloria seguro que te va a sugerir la canción de Mariah Carey

**Comment by MiriamVR** [comment]
Esta también mola 
https://www.youtube.com/watch?v=b3HvAbKtZtE

**Comment by gloriacaro97** [comment]
Yo veo la de Miriam, pero en el estilo de Juan Carlos, en plan, en instrumental.
https://www.youtube.com/watch?v=LiTdBtseL0Q

**Comment by AlvMur** [comment]
Me gusta, pero que no suene muy alta que eso es molesto. Con que suene flojito está bien
