### ISSUE TITLE
Posible mejora

### ISSUE THREAD

**Issue by AlvMur** [gloriacaro97/Despl-Grupo4-2020#8]
![imagen](https://user-images.githubusercontent.com/43762525/99985283-3a439880-2dae-11eb-9c41-274703f773c0.png)

He estado probando para mejorar la visibilidad del texto de la página y he estado probando poner como está en la imagen. No sé si os gusta o lo haríais de otra forma. Es que me parece que el texto sobre un rojo tan intenso no se vé bien.

**Comment by MiriamVR** [comment]
Me parece bien. ¿Son colores de la paleta?

**Comment by gloriacaro97** [comment]
Me parece perfe, pero pondría los colores acorde con los de los cards para que quedara uniforme

**Comment by MiriamVR** [comment]
Si, yo también usaría los colores que ya tenemos en la web.
Saludos
